/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 07-jan-2020 17:49:08 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

DROP TABLE IF EXISTS Alumni CASCADE
;
DROP TABLE IF EXISTS Company CASCADE
;
DROP TABLE IF EXISTS Organization_ CASCADE
;
DROP TABLE IF EXISTS Student CASCADE
;
DROP TABLE IF EXISTS User_ CASCADE
;
DROP TABLE IF EXISTS Evaluate CASCADE
;
DROP TABLE IF EXISTS Manages CASCADE
;

/* Create Tables */

CREATE TABLE User_
(
	Age_user varchar(255) NULL,
	Email_user varchar(255) NULL,
	Name_user varchar(255) NULL,
	Telephone_user varchar(255) NULL,
	UserID varchar(255) NOT NULL,
	CONSTRAINT PK_User_ PRIMARY KEY (UserID ASC)
)
;

CREATE TABLE Alumni
(
	AlumniID varchar(255) NOT NULL references User_(UserID),
	Experience varchar(255) NULL,
	PRIMARY KEY (AlumniID)
)
;

CREATE TABLE Evaluate
(
	AlumniID varchar(255) NOT NULL,
	CompanyID varchar(255) NOT NULL,
    Av_salary_ varchar(255) NULL,
    Efect_hours_ varchar(255) NULL,
	primary key (AlumniID,CompanyID),
    foreign key(AlumniID)
		references Alumni (AlumniID),
	foreign key(CompanyID)
		references Company (CompanyID)
)
;
CREATE TABLE Organization_
(	
	OrganizationID varchar(255) NOT NULL references User_(UserID),
	Clearance varchar(255) NULL,
	PRIMARY KEY (OrganizationID)
)
;

CREATE TABLE Student
(
	StudentID varchar(255) NOT NULL references User_(UserID), 
	Area_masters varchar(255) NULL,
	Current_year varchar(255) NULL,
	PRIMARY KEY (StudentID)
)
;

CREATE TABLE Company
(
	CompanyID varchar(255) NOT NULL,
    Name_company varchar(255) NULL,
	Contact_info varchar(255) NULL,
	General_info varchar(255) NULL,
    Eval_total varchar(255) NULL,
	Av_salary varchar(255) NULL,
    Efect_hours varchar(255) NULL,
    PRIMARY KEY (CompanyID)
)
;

CREATE TABLE Manages
(
	OrganizationID varchar(255) NOT NULL,
	CompanyID varchar(255) NOT NULL,
    Contact_change varchar(255) NULL,
    Info_change varchar(255) NULL,
    Time_ varchar(255) NULL,
    primary key (OrganizationID,CompanyID),
    foreign key(OrganizationID)
		references Organization_ (OrganizationID),
	foreign key(CompanyID)
		references Company (CompanyID)
)
;

LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\User_.csv'
INTO TABLE User_
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\r\n'
;

LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\Alumni.csv'
INTO TABLE Alumni
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\r\n'
;

LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\Evaluate.csv'
INTO TABLE Evaluate
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\r\n'
;

LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\Organization_.csv'
INTO TABLE Organization_
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\r\n'
;

LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\Student.csv'
INTO TABLE Student
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\r\n'
;

LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\Company.csv'
INTO TABLE Company
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\r\n'
;

LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\Manages.csv'
INTO TABLE Manages
FIELDS TERMINATED BY ';'
LINES TERMINATED BY '\r\n'
;




