/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 07-jan-2020 17:49:08 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Alumni` CASCADE
;

DROP TABLE IF EXISTS `Company` CASCADE
;

DROP TABLE IF EXISTS `Organization` CASCADE
;

DROP TABLE IF EXISTS `Student` CASCADE
;

DROP TABLE IF EXISTS `User` CASCADE
;

/* Create Tables */

CREATE TABLE `Alumni`
(
	`Experience` varchar(0) NULL,
	`AlumniID` varchar(0) NOT NULL,
	CONSTRAINT `PK_Alumni` PRIMARY KEY (`AlumniID` ASC)
)

;

CREATE TABLE `Company`
(
	`Av_salary` varchar(0) NULL,
	`Company_id` varchar(0) NULL,
	`Contact_info` varchar(0) NULL,
	`Efect_hours` varchar(0) NULL,
	`General_info` varchar(0) NULL,
	`Name_company` varchar(0) NULL,
	`CompanyID` varchar(0) NOT NULL,
	`AlumniID` varchar(0) NULL,
	CONSTRAINT `PK_Company` PRIMARY KEY (`CompanyID` ASC)
)

;

CREATE TABLE `Organization`
(
	`Clearance` varchar(0) NULL,
	`Role` varchar(0) NULL,
	`OrganizationID` varchar(0) NOT NULL,
	`CompanyID` varchar(0) NULL,
	CONSTRAINT `PK_Organization` PRIMARY KEY (`OrganizationID` ASC)
)

;

CREATE TABLE `Student`
(
	`Area_masters` varchar(0) NULL,
	`Current_year` varchar(0) NULL,
	`StudentID` varchar(0) NOT NULL,
	CONSTRAINT `PK_Student` PRIMARY KEY (`StudentID` ASC)
)

;

CREATE TABLE `User`
(
	`Age_user` varchar(0) NULL,
	`Email_user` varchar(0) NULL,
	`Name_user` varchar(0) NULL,
	`Tecnicoid` varchar(0) NULL,
	`Telephone_user` varchar(0) NULL,
	`UserID` varchar(0) NOT NULL,
	`CompanyID` varchar(0) NULL,
	CONSTRAINT `PK_User` PRIMARY KEY (`UserID` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Alumni` 
 ADD CONSTRAINT `FK_Alumni_User`
	FOREIGN KEY (`AlumniID`) REFERENCES `User` (`UserID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Company` 
 ADD CONSTRAINT `FK_Company_Alumni`
	FOREIGN KEY (`AlumniID`) REFERENCES `Alumni` (`AlumniID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Organization` 
 ADD CONSTRAINT `FK_Organization_Company`
	FOREIGN KEY (`CompanyID`) REFERENCES `Company` (`CompanyID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Organization` 
 ADD CONSTRAINT `FK_Organization_User`
	FOREIGN KEY (`OrganizationID`) REFERENCES `User` (`UserID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Student` 
 ADD CONSTRAINT `FK_Student_User`
	FOREIGN KEY (`StudentID`) REFERENCES `User` (`UserID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `User` 
 ADD CONSTRAINT `FK_User_Searches`
	FOREIGN KEY (`CompanyID`) REFERENCES `Company` (`CompanyID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1 
;
